
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace HiveSenseDisplay
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions

        Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;
        Gadgeteer.Modules.LoveElectronics.Button HappyButton;
        Gadgeteer.Modules.LoveElectronics.Button Mehbutton;
        Gadgeteer.Modules.GHIElectronics.Button SadButton;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            SadButton = new GTM.GHIElectronics.Button(4);
		
            HappyButton = new GTM.LoveElectronics.Button(6);
		
            Mehbutton = new GTM.LoveElectronics.Button(8);
		
            display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, 10);
		
            

        }
    }
}
